browzer:
  browser: "CHROME"
  headless: True
  remote: True
  selenium_grid_url: "http://127.0.0.1:4444/wd/hub"
  selenium_grid_port: 4444
  browser_resolution: "1280x1024"
  browser_version: "latest"
  driver_binary_path: "acquire"
  browser_capabilities: {}
  chrome_options: []
  base_url: ""
  explicit_waiting: 30.00
  polling_interval: 0.25
  page_source_capturing: False
  page_screenshot_capturing: False
  stack_trace_capturing: False
  javascript_clicks: False
  javascript_sendkeys: False
  default_selector: "css"
  driver_listener_module_class_path: ""
